config/routes.rb
Peerpressure::Application.routes.draw do

  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show]
  resources :todos, :only => [:create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/help',                                  to: 'static_pages#help'
  match '/add',                                   to: 'todos#new'
  match '/auth/:provider/callback',               to: 'authentications#create'
  match '/todos/:id/completed',                   to: 'todos#completed_toggle', :as => :toggle
  match '/twitter/:id/commit_tweet',              to: 'twitter#commit_tweet', :as => :commit_tweet
  match '/twitter/:userid/check_if_all_complete', to: 'twitter#check_if_all_complete', :as => :check_if_all_complete
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @todo = current_user.todos.build if signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if signed_in? %>
  <div class="row">
	<aside class="span4">
      <section>
        <%# <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/todo_form' %>
      </section>
    </aside>
 	<div class="span8">
		<h3>Todo List</h3>
		<%= render 'shared/feed' %>
	</div>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to ToDoOrDie</h1>
	<h2>Sometimes you just need your friends to hold you accountable to get things done!
		<br>ToDoOrDie is a <strong>24-hour time bomb that tweets if tasks are incomplete.</strong></h2>
	<strong>Step #1:</strong> Sign up and connect to your Twitter account<br>
	<strong>Step #2:</strong> Commit to a todo task that you want to complete in 24 hours<br>
	<strong>Step #3:</strong> If you do not complete your task within 24 hours, <strong>we'll tweet to your followers that you missed your goal!</strong><br><br>
	<%= image_tag "incompletetweet.png" %><br><br>


    <%= link_to "Sign up now!", authentications_path, 
                                class: "btn btn-large btn-primary" %>
	<br><br>
  </div>
<% end %>