config/routes.rb
Peerpressure::Application.routes.draw do

  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show]
  resources :todos, :only => [:create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/help',                                  to: 'static_pages#help'
  match '/add',                                   to: 'todos#new'
  match '/auth/:provider/callback',               to: 'authentications#create'
  match '/todos/:id/completed',                   to: 'todos#completed_toggle', :as => :toggle
  match '/twitter/:id/commit_tweet',              to: 'twitter#commit_tweet', :as => :commit_tweet
  match '/twitter/:userid/check_if_all_complete', to: 'twitter#check_if_all_complete', :as => :check_if_all_complete
 
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="todos">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>
	

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<span class="user">
		<%-# <%= link_to feed_item.user.email, feed_item.user % > -%>
	</span>
	<span class="content"><strong>Task: </strong><%= feed_item.todoitem %></span>
	<span class="timestamp">
		<strong>Committed on:</strong> <%= l feed_item.created_at.localtime, :format => :shorter %>
		<br>
		<% if feed_item.created_at + 24.hours > Time.now %>
			<strong>Deadline:</strong> <%= l (feed_item.created_at.localtime + 24.hours), :format => :shorter %>
		<% else %>
			<strong>Time's up</strong>
		<% end %>
		<br>
	</span>
	<% if current_user?(feed_item.user) %>
		<% if feed_item.complete %>
			<strong>Status:</strong> Complete
			<br>
			<%= link_to "NOT DONE", toggle_path(feed_item.id), 
			                            class: "btn btn-small btn-primary" %>
		<% else %>
			<strong>Status:</strong> Incomplete
			<br>
			<%= link_to "DONE", toggle_path(feed_item.id), 
			                            class: "btn btn-small btn-primary" %>
		<% end %>
		<br>
		<%= link_to "Delete", feed_item, method: :delete,
										 data: { confirm: "You sure?" },
										 title: feed_item.todoitem %>
	<% end %>
</li>

app/views/shared/_todo_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  I want to... 
  <div class="field">
    <%= f.text_field :todoitem, placeholder: "go to the gym" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
<a href="<%= user_path(current_user) %>">
  <%= current_user.email %>
</a>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.todos.count, "todo") %>
</span>