config/routes.rb
Peerpressure::Application.routes.draw do

  resources :authentications
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show]
  resources :todos, :only => [:create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/help',                                  to: 'static_pages#help'
  match '/add',                                   to: 'todos#new'
  match '/auth/:provider/callback',               to: 'authentications#create'
  match '/todos/:id/completed',                   to: 'todos#completed_toggle', :as => :toggle
  match '/twitter/:id/commit_tweet',              to: 'twitter#commit_tweet', :as => :commit_tweet
  match '/twitter/:userid/check_if_all_complete', to: 'twitter#check_if_all_complete', :as => :check_if_all_complete
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://twitter.com/felixthea">@felixthea</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", 'mailto:felixthea@gmail.com' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ToDoOrDie", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          	<li><%= link_to "Home", root_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to 'Register', new_user_registration_path %></li>
				<li><%= link_to "Sign in", authentications_url %></li>
			<% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
	  <% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>
      <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>